### PR TITLE
fix(runtime): array of vnode could not be patched

### LINKED ISSUE #26: Missing components when re-rendering with data change
## Description

标记了Prop的数据改变不是也会触发重新渲染的吗，但是现在就是标记为Prop的数据在改变后，也不会重新渲染

## Example

```tsx
@Prop({ default: [] })
list: any
// 这里做了一下请求之后把数据赋值给list..
return (
<>
  {this.list.map((_item) => (
    <div>1</div>
  ))}
</>
)
```

## Reproduction

https://github.com/wibus-wee/jwcjs-re-render-bug

### PR DESCRIPTION
**Pull request by wibus-wee**
fixed #26

### CODE REVIEW

**Comment by wibus-wee** [comment]
I marked `isNew` as `ture` for the new element in `VNode[]` (`diffRecursive()`). 

But in `updateDOM()`, `isNew` turn to `false` again

File: packages/runtime/utils/attrs.ts [hunk 1]
```diff
@@ -1,6 +1,17 @@
...
+export function removeAttrs(
+	vnode: VNode | VNode[],
+	attrs: string[] = ["isNew"]
+) {
+	if (vnode instanceof Array) {
+		for (const node of vnode) {
+			removeAttrs(node, attrs);
+		}
+		return {
+			vnode,
```
Comment (wibus-wee) [inline packages/runtime/utils/attrs.ts:12]: 这个地方是有问题的，写错了似乎

**Review by AkaraChen — APPROVED** [review]
